services:
  postgres-database:
    image: postgres:15.3
    container_name: app-database
    restart: always
    ports:
      - "5433:5432" # Expose Postgres on localhost:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data # Mount local ./postgres to container's data directory